-- 库存盘点功能数据表
-- 执行位置: Supabase Dashboard → SQL Editor（整个文件复制粘贴运行一次即可）

-- 盘点单（一次全店盘点一条记录）
CREATE TABLE IF NOT EXISTS stocktakes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status TEXT NOT NULL DEFAULT 'in_progress',      -- in_progress=进行中 / completed=已完成
  created_by TEXT NOT NULL DEFAULT '',             -- 盘点人
  note TEXT NOT NULL DEFAULT '',                   -- 备注
  total_items INTEGER NOT NULL DEFAULT 0,          -- 明细行数（商品×尺码）
  counted_items INTEGER NOT NULL DEFAULT 0,        -- 已清点行数
  gain_total INTEGER NOT NULL DEFAULT 0,           -- 盘盈合计件数（完成时计算）
  loss_total INTEGER NOT NULL DEFAULT 0,           -- 盘亏合计件数（完成时计算，正数表示亏）
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

-- 清点明细（每商品每尺码一行）
CREATE TABLE IF NOT EXISTS stocktake_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stocktake_id BIGINT NOT NULL REFERENCES stocktakes(id) ON DELETE CASCADE,
  sale_id TEXT NOT NULL DEFAULT '',
  shelf_no TEXT NOT NULL DEFAULT '',               -- 盘点时货架号快照（排-货架-层）
  name TEXT NOT NULL DEFAULT '',
  photo TEXT NOT NULL DEFAULT '',
  size INTEGER NOT NULL DEFAULT 0,
  expected_qty INTEGER NOT NULL DEFAULT 0,         -- 系统库存（创建时快照 = 入库 − 已售 + 已退）
  counted_qty INTEGER,                             -- 实点数（NULL=未清点）
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_stocktake_items_stocktake ON stocktake_items(stocktake_id);
CREATE INDEX IF NOT EXISTS idx_stocktake_items_shelf ON stocktake_items(shelf_no);
CREATE INDEX IF NOT EXISTS idx_stocktakes_status ON stocktakes(status);
